title: Home | JWForever5504
theme: minima
base_url: /home

minima:
    date_format: "%b %d, %y"
    
header_pages:
  - index.md
  - links.md
  - downloads.md
  - about_me.md
  
google_analytics: G-44T3X0M2KK

youtube_username: "channel/UCW_dsmLJe5dIrVw34y9IOew"
mcpedl_username: "user/jwforever5504"
