theme: minima
title: Home | JWForever5504
header_pages:
  - home.md
  - downloads.md
  - about_me.md
social_links:
  - { platform: youtube, user_url: "https://www.youtube.com/channel/UCW_dsmLJe5dIrVw34y9IOew" }
  - { platform: mcpedl, user_url: "https://mcpedl.com/user/jwforever5504" }
