title: Home | JWForever5504
theme: minima
base_url: /home
date_format: "%b %d, %y"
    
header_pages:
  - index.md
  - links.md
  - downloads.md
  - about_me.md
  
google_analytics: G-44T3X0M2KK

youtube: channel_name
youtube_channel: UCW_dsmLJe5dIrVw34y9IOew
youtube_channel_name: channel_name
youtube_username: channel_name
